spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.9.20:8848
    sentinel:
      transport:
        port: 8720
        dashboard: localhost:8080

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  sentinel:
    enabled: true
